// this file was generated by the xRM Test Framework VS Extension

#region Imports

using System;
using Microsoft.Xrm.Sdk;

#endregion

namespace LinkDev.AutoNumbering.Plugins.AutoNumber.Config.Post
{
	/// <summary>
	/// DEPRECATED
	/// </summary>
	public class UpdateConfigTriggerId : IPlugin
	{
		public void Execute(IServiceProvider serviceProvider)
		{ }
	}
}
